danvk/dygraphs

plugins/legend.js
I've run into issue with legend position when it was clipped by overflow: hidden (using fixed width modal to show the chart), so I think it might make more sense to switch position when it would go outside chart area.
Also proposing 20->50px to show more points around currently highlighted one. When you move your mouse quickly, it might jump inside legend area which then stops following and stays put - especially when you have wider gaps in your data (even as you move your mouse over the gap, legend stays in one place until you reach next point).
=> legend: follow positioning fixes

extras/synchronizer.js
Urgh. This is a start, but it creates a new bug: cross-contamination between graphs. See, for example, http://rths.us/viz.cgi?from=2015-02-05&to=2015-02-19&state=serieses&siteid=4&config=config.json&seriesid-2600=15&seriesid-2604=16&seriesid-2605=17&seriesid-2125=18&seriesid-2602=33&seriesid-2603=34&seriesid-2606=35&seriesid-2607=36&seriesid-2124=37&seriesid-2126=38
The graphs all have the same Y scale, even though they have different data. So the data is visible on some graphs, but not visible on other graphs. Also, if I move the cursor within the first graph, the second graph moves jerkily if at all. Same with the third. But if I put my cursor within the second graph, the first and third graphs move smoothly.
Also, I don't see any good way to test this, because it fixes a bug when a …
=> delay synchronizing until all the dygraphs are ready.

auto_tests/misc/local.html, auto_tests/tests/visibility.js, dygraph.js
Currently, each visibility change triggers a redraw, which causes functionality like hiding/showing all series (or applying a filter) to be very slow. This change allows setVisibility() to accept an array instead of a single numbers so that the redraw only happens after the visibility of multiple series has been updated.
This replaces https://github.com/danvk/dygraphs/pull/559
=> update setVisibility to be able to set the visibility of multiple series at once

.travis.yml, tests/plotters.html
`tests/plotters.html` was broken before (no charts rendered).
Also updates us to use Travis-CI's [container-based architecture][1], which should make builds start faster.
[1]: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Update reference to drawGrid option

auto_tests/tests/Util.js, auto_tests/tests/axis_labels-deprecated.js, auto_tests/tests/axis_labels.js, auto_tests/tests/callback.js, auto_tests/tests/custom_bars.js, auto_tests/tests/error_bars.js, auto_tests/tests/formats.js, auto_tests/tests/interaction_model.js, auto_tests/tests/missing_points.js, auto_tests/tests/pathological_cases.js, auto_tests/tests/range_selector.js, auto_tests/tests/range_tests.js, auto_tests/tests/rolling_average.js, auto_tests/tests/sanity.js, auto_tests/tests/selection.js, auto_tests/tests/simple_drawing.js, auto_tests/tests/stacked.js, auto_tests/tests/to_dom_coords.js, auto_tests/tests/update_while_panning.js, package.json, scripts/check-no-only.sh
Most of these were "using default labels".
Also adds a precommit hook to ensure that `.only` in a test is never committed. I've made this mistake a few times in the last few days.
=> Remove all test warnings

package.json, src/dygraph.js
Today, when loading dygraphs from NPM via browserify you need to include:
```javascript
var Dygraph  = require('dygraphs/dygraph-combined.js');
```
Being able to do this:
```javascript
var Dygraph  = require('dygraphs');
```
Is preferable.
**UPDATE**
Dygraphs doesn't have a `module.exports` statement, so it can't be loaded via Browserify at all. This PR also includes a fix for this.
=> Load dygraph-combined when loading from NPM

src/dygraph-utils.js
Hello,
when you put chart inside element that's fullscreen (using fullscreen api), range selections start at wrong positions (current findPos clearly uses original position, not zoomed).
If I'm not mistaken, original findPos uses some 12 years old code that was created because getBoundingClientRect didn't exist back then. So I'm proposing this simpler version. Or is there some reason to keep the old one?
=> Fix range selection when chart is located inside fullscreen element

DEVELOP.md, auto_tests/chrome.karma.conf.js, auto_tests/karma.conf.js, auto_tests/tests/error_bars.js, auto_tests/tests/utils_test.js, package.json, src/dygraph-utils.js
The behavior in dygraphs 1.0.x was also broken, though less egregiously. It would parse `rgba`-style colors as black, so the fill would be some sort of gray.
The new behavior is to use the `rgba` color for the series line. For the fill, the alpha value is set to `fillAlpha`.
This should result in a small speedup, since I'm bypassing DOM manipulation to parse simple color strings.
I also took the opportunity to split off a `karma.conf.js` file to facilitate debugging in browser.
Fixes #517
=> Handle rgba() colors & error bars properly

auto_tests/tests/fast_canvas_proxy.js, src/dygraph-canvas.js
Fixes #558
The fix is largely as described in #555, though it needed to be a two-sided check for gaps, not just a one-sided check.
=> Fix and regression test for fast proxy artifacts.

auto_tests/tests/per_series.js, src/dygraph-canvas.js, tests/fillGraph-alpha.html
Changed the way that the fillAlpha option is processes in the _fillPlotter function in order to allow for per-series configuration.   Previously when fillGraph was set, only the global option was recognized.
=> Allow fillAlpha to be set on a per-Series basis when fillGraph option is used.

auto_tests/chrome.karma.conf.js, auto_tests/karma.conf.js, auto_tests/tests/synchronize.js, src/extras/synchronizer.js
My previous solution to keeping/re-attaching callbacks on detach() was clearly completely wrong, so this should hopefully fix it
=> Fix previous callbacks

auto_tests/tests/visibility.js, src/dygraph.js
This PR enables setVisibility to accept value as an array, so one can do:
```javascript
graph.setVisibility([1,2,3], [true,false,true]);
```
If the boolean array have a different length of the num argument, then an error is thrown.
Previous behavior hasn't changed.
Tests added for both success and fail cases.
Additionally, this patch solves the array check issue related in https://github.com/danvk/dygraphs/pull/560#discussion-diff-36852612
If I missed something, please let me know and I'll try to adjust the code.
=> Add support to boolean array in setVisibility function

src/extras/super-annotations.js
When I try to use the `SuperAnnotations` plugin I get the following error message when I click on a point to create a new annotation:
```
dygraph.js:227 Uncaught TypeError: opts is not a function
```
This PR fixes this error by providing the proper arguments to `xfv.call` inside `annotations.getTemplateHTML` method.
=> Adding xOptView for xfv.call to work properly

DEVELOP.md, auto_tests/tests/highlight_series_background.js, scripts/run-tests.sh, src/dygraph-default-attrs.js, src/dygraph-options-reference.js, src/dygraph.js
This revives #602.
See also #285 
This is a WIP — trying to speed up the selection fade animation exposed an assumption that `animateSelection_` is making about how `repeatAndCleanup` works. It assumes that if it asks for 10 frames, it will get 10 frames. But that's not necessarily the case.
=> Add highlightSeriesBackgroundColor option

auto_tests/tests/plugins_legend.js, src/dygraph-options-reference.js, src/plugins/legend.js, tests/legend-formatter.html
This is intended to be a catch-all for legend formatting needs. This [comes][1] [up][2] [often][3] in Stack Overflow [questions][4] which can't be easily answered with `valueFormatter`. Nowadays I wave my hands and say "write your own legend, either as a plugin or using `highlightCallback` and `unhighlightCallback`." This is a simpler option.
The `legendFormatter` is repeatedly called with a `data` object describing the selection or lack of selection. It contains all the information you need to generate a standard legend (e.g. formatted values), but there's nothing preventing you from doing something crazier on your own.
For example, here's what a simple `legendFormatter` might look like:
```javascript
function legendFormatter(data) {
if (data.x == null) return '';  // no selection
return …
```
=> Add a legendFormatter option

src/iframe-tarp.js
The IFrameTarp.prototype.cover function calls `findPos` from the `dygraph-utils.js` file but does not import it. 
This fixes #724
=> Bugfix: Import missing dygraph-utils.js

src/extras/synchronizer.js
Fixes issue #760 by checking for new options before calling `updateOptions` with an extra flag.
=> Check for new options before updating synchronised graphs (Fixes #760)

auto_tests/tests/data_api.js, src/dygraph.js
Calling `indexFromSetName` on the last set would fail if its visibility was set to false, because the set's label would not be added to the internal list of sets (stored in the `setIndexByName_` variable).
This pull request fixes the issue, and adds a test to check that it works.
The test added to `tests/data_api.js` provides an example that currently fails, and now passes with this fix.
=> Bug fix: indexFromSetName on invisible sets

src/dygraph.js
Synchronization breaks up if this case is not checked. Fix has been
proposed in the bugreport.
=> Check that setRow is not negative, fixes #644.

DEVELOP.md, auto_tests/tests/date_formats.js, src/dygraph-utils.js, tests/labelsDateMilliseconds.html
1st commit add a feature to Dygraph.dateString_: shows milliseconds if any.
2nd commit fixes a typo in dateAxisLabelFormatter.
=> Dygraph.dateString_: shows milliseconds if any.

src/dygraph-options.js
Closes #675 
These have been deprecated for 4+ years, so everyone's had a chance to see the warning.
=> Make old-style per-series options throw

src/dygraph-canvas.js, src/dygraph-utils.js
Closes #608 
I'm not sure if/when this bug was fixed. But I'd rather not be in the business of working around browser bugs. The Android browser's market share is low at this point and Chrome supports canvas just fine.
=> Remove isAndroid checks

auto_tests/tests/range_selector.js, src/dygraph-options-reference.js, src/plugins/range-selector.js
Closes #429
I don't love the interaction with `showInRangeSelector`, but I don't see a better way to handle it. Once you set `showInRangeSelector` on any series, you're managing this manually. Regardless of visibility.
=> Only include visible series in range selector

src/dygraph-interaction-model.js
=> Fix #816; remove references to valueWindow

src/dygraph-interaction-model.js, src/dygraph.js, tests/old-yrange-behavior.html
Add demo of how to restore the dygraphs 1.x zoom out behavior.
=> Make dblclick event cancelable.

docs/site.css, docs/ssi_server.py, gallery/number-format.js, scripts/check-no-only.sh, src/dygraph-options-reference.js, src/dygraph-utils.js, src/dygraph.js, tests/number-format.html
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes

dygraph-externs.js
1. The second argument of getOption should be marked as optional per
jsdoc at: http://dygraphs.com/jsdoc/symbols/Dygraph.html#getOption
2. 'boolean' is typo'd as 'Boolean' in updateOptions.
=> Fix two inconsistencies in dygraph-externs.js

dygraph-externs.js
Please read the guide to making dygraphs changes:
http://dygraphs.com/changes.html
Pull Requests will only be accepted if:
- You clearly explain what you're adding and why you believe it's an
improvement. For example: "Fixes issue #123".
- You adhere to the style of the rest of the dygraphs code base.
- You write an `auto_test` for the code that you're adding.
Be sure to document any new options you add. Also be aware that PRs which add
options are likely to be rejected. dygraphs already has many options. If you
can fit your feature into one of those or implement it as a plugin, it will be
more likely to get merged.
=> Make setAnnotations' boolean parameter optional.

gallery/interaction.js
Demo named "Custom interaction models" in Dygraphs Gallery breaks further navigation in the gallery. When a user reached the interaction demo it was not possible to navigate away from it anymore.
=> Fix gallery navigation from interaction demo

auto_tests/tests/hidpi.js, src/dygraph-options-reference.js, src/dygraph.js, src/plugins/range-selector.js
Let me know about any desired changes or adjustments. I hand tested the range-selector gallery example with `pixelRatio: 3`, and it seems to behave the same and properly force scaling; the implementation followed a definitive pattern of overriding utils.getContextPixelRatio()
=> Added pixelRatio option to override canvas upscaling. Resolves #876, test included.

dygraph-externs.js
=> Add missing semicolon in externs

auto_tests/tests/data_types.js, src/dygraph.js
Fixes problem described in https://github.com/danvk/dygraphs/issues/984
Date format 20035000 is problematic, because it causes error:
Couldn't parse 20035000 as a date
...
Couldn't parse 20251000 as a date
=> Fixes issue #984 (Couldn't parse 20035000 as a date)

src/dygraph-tickers.js
I was [idly searching github](https://github.com/search?q=365.2524&type=code) for bugs and found that many references to the constant 365.2524 originate from this library. The actual constant is [365.2**4**2**5**](https://en.wikipedia.org/wiki/Gregorian_calendar). It doesn't really matter at all, but I thought it would be nice to correct it.
=> There's 365.2425 days in a gregorian year

src/dygraph-interaction-model.js
In dygraph-interaction-model.js, DygraphInteraction.moveTouch, the following is done:
```
g.dateWindow_ = [
c_init.dataX - swipe.dataX + (context.initialRange.x[0] - c_init.dataX) / xScale,
c_init.dataX - swipe.dataX + (context.initialRange.x[1] - c_init.dataX) / xScale
];
```
However, it seems that swipe.dataX is not properly scaled. It should be:       
`c_init.dataX - swipe.dataX / xScale + (context.initialRange.x[0] - c_init.dataX) / xScale`
In startTouch(), pageX, pageY is not appropriate for the calculation of dataX, dataY. This causes serious problems in the calculation of context.initialPinchCenter. The wrong calculations affect pinch-zoom when the x or y range is small and the graph div is farther to the bottom or right of the page.
For example, see …
=> two bugs fixed in the calculations of pinch-zoom

src/dygraph.js
As described in #781, the library makes wrong decisions when the y-range is zero.
In such cases (`y0 === y1`), this PR changes:
```js
y0 -= 0.5
y1 += 0.5
```
so that the chart is properly rendered.
=> fixes issue #781

src/plugins/legend.js
This adds the `row` index to the structure passed to the `legendFormatter`. Having the index enables quick indexing of external, unplotted auxiliary data for a point.
=> add data index to legendFormatter data

docs/annotations.html
Documentation about xval option for g.setAnnotations() was missing. Added in this commit.
I was in a situation where I had to use xval. X values were dates passed as Date objects in GViZ format. So, the only sensible thing I could pass to setAnnotations was the milliseconds (.getTime()). 
So I needed the xval option and I could not use the x option.
=> documentation about annotations xval option

src/plugins/grid.js
```ctx.closePath();``` makes second draw of the line. With solid line there is no difference but performance, but when the line has any pattern, this second draw makes a mess.
=> Fix for double paint of grid of x-axis

src/plugins/legend.js
This is done by checking the current highlighted series.
=> Calculate legend positioning relative to closest data point

auto_tests/tests/axis_labels.js, auto_tests/tests/multiple_axes.js, auto_tests/tests/xhr.js, scripts/generate-coverage.sh, src/dygraph-options-reference.js, src/dygraph-utils.js
This fixes #994 and #571 by:
- using the correct SI units for `labelsKMB`
- using the correct IEC 60027-2 units for `labelsKMG2`
- unless `labelsKMB` is _also_ given, in which case the “legacy” units (basically the same as `labelsKMB` except with `K` instead of `k` for Kibi) are used instead
- for the nōn-KMB KMG2 case, use binary float-style “`p-10`” notation for the “small” units; the way `numericTicks()` operates makes it basically necessary to have “small” units for all labelling styles
- fix the KMG2-related small label tests by picking values that make checking the labels properly possible
=> fix label units

src/dygraph-layout.js
If there are multiple same x-valued points, the annotation would be rendered multiple times.
=> Fix duplicate annotation when having duplicate points.

src/extras/crosshair.js
I needed this functionality for my graphs because I am working in a dark theme. The default color was hardly visible.
Maybe the option should be called 'color' instead of strokeStyle, or maybe color can be an object inside strokeStyle
But I let it remain consistent with the current variables for now.
What do you think?
=> Added strokeStyle option to crosshair plugin to allow color choice.

src/dygraph.js, src/extras/synchronizer.js
Currently, there appears to be either a bug or a surprising behavior with extras/synchronizer.js where the synchronizer's selection of a data series in the synchronized graph fails to trigger the user's highlightCallback function.
This pull request adds a parameter to setSelection that allows specifying triggering of highlightCallback, which is then used by synchronizer.js to trigger the callback.
All existing tests from "npm run test" appear to still pass.
=> Allow setSelection to trigger highlightCallback and do so in synchronizer

gallery/drawing.js, src/extras/synchronizer.js
This pull request fixes the broken zoom functionality  and console errors in the drawing demo.  It simply adds the willDestroyContextMyself attribute, and removes the now unimplemented functions in the defaultInteractionModel.  Comments have also been added to explain to users why calls are missing.
Sorry about the double commit, still getting a handle on pull request functionality.  13887ef corrects a problem where synchronizer.js would block the users drawCallback when updating the zoom of connected charts.
=> Fix issue #611 in the drawing demo gallery

src/extras/crosshair.js
It is difficult to provide an example to test as the problem was discovered when using electron + react desktop application, but here is description and a screenshot of the error.
Having several graphs synchronized using synchronize plugin and having crosshair plugin used on them, doing these steps causes the error:
1. Zooming in one of the synced graphs
2. Moving cursor in and out of application bounds right after that (without clicking anywhere after zooming in)
Checking of `selPoints_.length !== 0` fixed it
=> Crosshair plugin runtime error on moving cursor out fix

src/extras/crosshair.js
Crosshair plugin creates canvas to draw its lines, but if the graph is small enough, this canvas can block interaction with other elements until you hover over a graph giving it a chance to resize. Canvas initializes with 300x150 which is default [Canvas element - Wikipedia](https://en.wikipedia.org/wiki/Canvas_element#:~:text=By%20default%2C%20both%20the%20canvas,and%20150%20screen%20pixels%20high.)
In the example below it overlaps the '+' button preventing clicking it
To fix it I have set the size to [0,0] in plugin constructor.
=> Crosshair plugin - initial canvas size fix

src/dygraph-layout.js
Some users may improperly define the range of their axes, leading to points being drawn outside of the chart area. In the worst cases, if all points are out of range, the chart will not be drawn at all.
Adding a warning can help users identify this issue and correct it.
Note that may spew a lot of warnings if their are a lot of points.
---
Such a warning helped me debug the usage of netdata. See https://github.com/netdata/netdata-cloud/issues/1048
=> Warn if points are out of range

src/dygraph-tickers.js
I needed this ticker and noticed it didn't already exist. Obviously, please feel free to reject this if you'd prefer clients to write their own tickers to do this instead of exposing this convenience function.
I'd like to write tests for this, but wasn't able to run them so they're not included. All feedback on this PR is welcome! Thanks :)
=> Define `Dygraph.integerTicks`

src/extras/crosshair.js
When the graph is zoomed in, crosshair can select points out of view area, drawing lines off graph.
Below is example where the area on the left is caused by `axisLabelWidth`, so it is inside crosshair drawing canvas.
The same happens on the right side when using `rightGap`. Filtered by checking `selectedPoint.x` to be in [0,1]
=> Crosshair plugin - out of graph bounds selection filter

src/extras/crosshair.js
Crosshair draws its lines at position +0.5 of pixel size to get crisp lines, but if the selected point is at the end of graph, this results in drawing the line off-graph. To avoid this and get the line visible, the `rightGap` option has to be set 1+.
Below is two graphs, which has rightGap = 1 and 0 respectively
I thought about several solutions, but it seems like just fixing the edge case fits best
=> Crosshair plugin - last point selection edge case visual fix

auto_tests/tests/highlight_series_background.js, src/dygraph.js
Selection overlay animation progresses the alpha value by 0.1 in each frame, regardless of the time between the frames. If CPU is busy and can't render enough frames, the animation can lag and finish in wrong state (with lower overlay alpha than expected). It's been mitigated for clearSelection case, which will be eventually called regardless of number of rendered frames, but it's handled as special case, which is rather messy.
The callback sent to `repeatAndCleanup()` in `animateSelection_` so far ignored the frame number sent by `repeatAndCleanup()`.
The code was assuming that it will be called `steps` time, which is not true if CPU is saturated and there are longer intervals between frames then expected - frames in the middle will be dropped. `repeatAndCleanup()` guarantees that it …
=> Fix selection fade frame progression

src/extras/synchronizer.js
Having several graphs synced, I wanted their vertical zooming to be independent. Setting synchronizer `range` option to `false` currently does that, but only partially.
1. If you are not x-zoomed in, then it works when you y-zoom one of the graphs for the first time, but if you y-zoom another graph after that, it resets first one.
2. If you are x-zoomed in, then it partially preserves vertical zooms, but still reset graphs depending on their position in the syncing graphs array.
For the first case I found that the source is `arraysAreEqual(a, b)` returning `false` while comparing x-axis arrays when both arrays are `null`. Since in dygraph null x axis (dateWindow) array means 'fully zoomed out', this should be treaten as equal zooming ranges. Adding a check like this
```
function …
```
=> Synchronizer plugin vertical zoom ignorance fix

src/dygraph-utils.js
This fixes violation reports in console (at Verbose level)
Happens on graph creation, can be checked on https://dygraphs.com/
=> Fix event listener violation for touchstart, touchmove event
