danvk/dygraphs

auto_tests/tests/Util.js
auto_tests/tests/plugins_legend.js
auto_tests/tests/range_selector.js
src/dygraph-utils.js
src/plugins/range-selector.js

Add a few tests, delete some dead code. Coverage should rise.

Coverage cleanup

---

docs/users.html

Dan, in our email conversation the other day, you suggested that you would consider adding us (HowManyDiapers.com) to the user list if I made a pull request. I've tried to match the formatting of the other items on the page as closely as possible. Thank you for your consideration.

Added HowManyDiapers.com to users.html page

---

.travis.yml

This makes tests start dramatically faster.

Use Travis container architecture

---

auto_tests/tests/callback.js
src/dygraph.js

Set this for drawCallback

---

extras/crosshair.js
tests/crosshair.html

This is a cleaned up version of #299.

Crosshair plugin

---

docs/users.html

Updating Great Lakes Dashboard entry. Prior link was dead.
Apologies for earlier confusion. This is a first time doing a pull request for me...

Updating users.html on source master

---

src/extras/synchronizer.js

Fix true/false redraw blocking bug in synchronizer

---

.travis.yml

This uses my new [travis-weigh-in][1] script.
[1]: https://github.com/danvk/travis-weigh-in

Track code size on PRs

---

src/dygraph-utils.js
src/dygraph.js
src/iframe-tarp.js
src/plugins/range-selector.js

See #383 — ES6 modules make it much easier to add new files

Split out IFrameTarp module

---

gallery/gallery.css

Chart overlaps "Edit in jsFiddle" button

---

auto_tests/tests/draw_gap_edge_points.js
src/dygraph-canvas.js

Fixes issue #745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danvk/dygraphs/746)

Bugfix: Unwanted drawn point when prevCanvasX is 0

---

src/dygraph-layout.js
src/plugins/axes.js
src/plugins/grid.js
tests/label_v.html

Implement label_v

---

auto_tests/tests/plugins_legend.js
src/dygraph.js

Set x appropriately for series but not point selection

---

docs/tutorial.html

Remove gadget links from tutorial

---

docs/annotations.html
src/plugins/annotations.js
tests/annotation.html

I haven't find a way to set color and width for annotation line, I have added option to set that.
PS. I was not sure against which branch I should create PR, so created against master.

[Feature Request] Provide option to set color and width for annotation line

---

gallery/link-interaction.js
package.json
tests/link-interaction.html

Add a:visited style to link-interaction

---

scripts/generate-download.py

See https://stackoverflow.com/questions/48488444/how-to-set-annotations-when-using-the-candle-plotter

Use link href, not link src

---

src/dygraph.js

Clear graph when numAxes goes from 1 -> 2 in updateOptions

---

auto_tests/tests/PixelSampler.js
auto_tests/tests/css.js
auto_tests/tests/custom_bars.js
auto_tests/tests/range_selector.js
auto_tests/tests/selection.js
auto_tests/tests/update_options.js

Fixes #1024
There was never any intention for these test files to be different from the others.

Add explicit MIT license to some test files

---

src/dygraph.js

Fixes #962 'Cannot read property 'length' of undefined' issue

---

src/plugins/legend.js

Please read the guide to making dygraphs changes:
http://dygraphs.com/changes.html
Pull Requests will only be accepted if:
- You clearly explain what you're adding and why you believe it's an
improvement. For example: "Fixes issue #123".
- You adhere to the style of the rest of the dygraphs code base.
- You write an `auto_test` for the code that you're adding.
Be sure to document any new options you add. Also be aware that PRs which add
options are likely to be rejected. dygraphs already has many options. If you
can fit your feature into one of those or implement it as a plugin, it will be
more likely to get merged.

Fixes issue #853
